"""Generate kernelbox-compatible test scripts from torch-graph H5 files.

Reads the grouped tensor dumps and replay scripts from an H5 file produced by
torch-graph's ``dump_grouped_tensors`` and generates standalone Python files that
work with ``kbox watch`` / ``kbox.iterate()``.

Generated files follow the kernelbox contract:
  - ``init_once()`` returns ``{"h5": "data/<name>.h5"}``
  - ``run(inputs)`` uses ``inputs.<name>`` attribute access
  - Kernelbox handles tensor loading, comparison, and hot-reload
"""

from __future__ import annotations

import os
import re
import textwrap
from dataclasses import dataclass, field
from pathlib import Path

import h5py
import torch

from torch_graph._utils import load_h5_tensors, short_name as _short_name

# ── Name mapping ─────────────────────────────────────────────────────────────

_SHORT_RE = re.compile(r"^p(\d+)$")
_SHORT_D_RE = re.compile(r"^d(\d+)$")


def _long_name(name: str) -> str:
    """H5 short name -> FX name: p6 -> primals_6, d3 -> tangents_3."""
    m = _SHORT_RE.match(name)
    if m:
        return f"primals_{m.group(1)}"
    m = _SHORT_D_RE.match(name)
    if m:
        return f"tangents_{m.group(1)}"
    return name


def _dataset_node_name(ds_name: str) -> str:
    """Extract the node name from 'input::fp32::2x16x32___add_3'."""
    parts = ds_name.split("___")
    if len(parts) >= 2:
        return parts[-1]
    return ds_name


def _fx_to_h5(fx_name: str, available: set[str]) -> str | None:
    """Resolve an FX name to its H5 tensor key, or None if not stored."""
    short = _short_name(fx_name)
    if short in available:
        return short
    if fx_name in available:
        return fx_name
    return None


# ── Data structures ──────────────────────────────────────────────────────────


@dataclass
class GroupInfo:
    """Metadata for one H5 group (line/module/op)."""

    index: int
    name: str  # e.g. "005_model.py:22 [blocks.0] | qkv = self.c_attn(x)"
    path: str  # full H5 path: "forward/line/005_model.py:22 ..."
    section: str  # "forward" or "backward"
    strategy: str  # "line" or "module"
    all_node_names: list[str]
    replay_script: str
    source_code: str
    source_file: str
    source_line: int
    module_path: str
    module_type: str
    # Derived: external input/output node names (H5 short names)
    input_nodes: list[str] = field(default_factory=list)
    output_nodes: list[str] = field(default_factory=list)


@dataclass
class UniqueGroupInfo:
    """A set of structurally identical H5 groups (same aten ops, different tensors).

    Generated by ``detect_unique_groups()`` — one ``run()`` function tests all instances.
    """

    fn_name: str  # generated function name, e.g. "layer_norm"
    module_type: str  # e.g. "LayerNorm"
    source_line: int  # source line (shared across instances)
    source_desc: str  # short human description, e.g. "model.py:48 | x = x + self.attn(...)"
    groups: list[GroupInfo]  # the instances (2+)
    normalized_script: str  # shared normalized replay
    # Per-instance mappings: generic_name -> actual FX name
    input_maps: list[dict[str, str]]
    output_maps: list[dict[str, str]]
    # Ordered generic names (used in run() and data files)
    generic_inputs: list[str]
    generic_outputs: list[str]


# ── H5 reading ───────────────────────────────────────────────────────────────


def _available_tensors(h5_path: str) -> set[str]:
    """Return the set of tensor names stored in /tensors/."""
    with h5py.File(h5_path, "r") as f:
        return set(f["tensors"].keys())


def _parse_replay_inputs(replay_script: str) -> list[str]:
    """Extract unique input names from a replay script (FX names)."""
    return list(dict.fromkeys(re.findall(r'inputs\["(\w+)"\]', replay_script)))


def _parse_replay_out(replay_script: str) -> list[str]:
    """Extract unique output names from a replay script, ordered by last assignment."""
    # Find all output assignments in order
    all_out = re.findall(r'outputs\["(\w+)"\]\s*=', replay_script)
    # Deduplicate preserving last occurrence
    seen: dict[str, int] = {}
    for i, name in enumerate(all_out):
        seen[name] = i
    return [name for name, _ in sorted(seen.items(), key=lambda x: x[1])]


def _replay_last_out(replay_script: str) -> list[str]:
    """Output names from the final lines — the group's most meaningful results.

    When trailing lines are getitem (tuple unpacking), returns the extracted
    elements, not the tuple-producing op (which holds a tuple, not a tensor).
    """
    lines = replay_script.strip().splitlines()
    result = []
    for line in reversed(lines):
        m = re.match(r'\s*outputs\["(\w+)"\]\s*=', line)
        if m:
            if "operator.getitem" in line:
                result.append(m.group(1))
            else:
                if not result:
                    result.append(m.group(1))
                break
        else:
            break
    result.reverse()
    return result


def _group_dataset_nodes(grp: h5py.Group) -> tuple[list[str], list[str]]:
    """Return (input_nodes, output_nodes) from group-level datasets."""
    inputs, out = [], []
    for ds_name in grp.keys():
        item = grp[ds_name]
        if not isinstance(item, h5py.Dataset):
            continue
        node = _dataset_node_name(ds_name)
        if ds_name.startswith("input::"):
            inputs.append(node)
        elif ds_name.startswith("output::"):
            out.append(node)
    return inputs, out


def _discover_sections(f: h5py.File) -> list[str]:
    """Discover section paths from H5 file metadata or structure.

    Returns section paths like ``"forward/line"``, ``"backward/line"``,
    ``"groups"``, ``"line"``, etc.
    """
    if "_meta" in f:
        meta_sections = list(f["_meta"].attrs.get("sections", []))
        if meta_sections:
            return meta_sections
    # Fallback: scan top-level groups
    skip = {"tensors", "scripts", "_meta"}
    return [k for k in f.keys() if k not in skip]


def list_groups(h5_path: str, section: str | None = None, strategy: str = "line") -> list[GroupInfo]:
    """Enumerate groups in an H5 file with metadata.

    Discovers sections from file metadata rather than assuming a fixed layout.
    Works with both multi-graph (``forward/line``, ``backward/line``) and
    single-graph (``line``, ``groups``) H5 structures.
    """
    groups: list[GroupInfo] = []

    with h5py.File(h5_path, "r") as f:
        available_sections = _discover_sections(f)

        # Filter to matching sections
        candidates = []
        for sec_path in available_sections:
            # Multi-graph: "forward/line", "backward/module" etc.
            if "/" in sec_path:
                sec_kind, sec_strat = sec_path.split("/", 1)
                if section and sec_kind != section:
                    continue
                if sec_strat != strategy:
                    continue
                candidates.append((sec_path, sec_kind))
            else:
                # Single-graph: "line", "module", "groups"
                # "groups" is the default label for a single strategy + single graph
                if sec_path != strategy and sec_path != "groups":
                    continue
                # Use the requested section as kind (default to the path itself)
                candidates.append((sec_path, section or sec_path))

        for sec_path, sec_kind in candidates:
            if sec_path not in f:
                continue
            parent = f[sec_path]
            for i, name in enumerate(sorted(parent.keys())):
                grp = parent[name]
                attrs = grp.attrs
                replay = attrs.get("replay_script", "")
                if not replay:
                    continue

                ann = list(attrs.get("all_node_names", []))
                input_nodes, output_nodes = _group_dataset_nodes(grp)

                info = GroupInfo(
                    index=i,
                    name=name,
                    path=f"{sec_path}/{name}",
                    section=sec_kind,
                    strategy=strategy,
                    all_node_names=ann,
                    replay_script=replay,
                    source_code=attrs.get("source_code", ""),
                    source_file=attrs.get("source_file", ""),
                    source_line=int(attrs.get("source_line", 0)),
                    module_path=attrs.get("module_path", ""),
                    module_type=attrs.get("module_type", ""),
                    input_nodes=input_nodes,
                    output_nodes=output_nodes,
                )
                groups.append(info)

    return groups


# ── Script generation ────────────────────────────────────────────────────────


def _needs_inf(replay_script: str) -> bool:
    """Check if the replay script uses bare `inf` (e.g. `-inf`)."""
    return bool(re.search(r'\binf\b', replay_script))


def _needs_math(replay_script: str) -> bool:
    """Check if the replay script uses `math.` functions."""
    return bool(re.search(r'\bmath\.', replay_script))


def _build_input_mapping(replay_script: str, available: set[str]) -> dict[str, str]:
    """Map replay-script input names (FX) to H5 tensor keys."""
    fx_inputs = _parse_replay_inputs(replay_script)
    mapping: dict[str, str] = {}
    for fx_name in fx_inputs:
        h5_key = _fx_to_h5(fx_name, available)
        if h5_key is not None:
            mapping[fx_name] = h5_key
    return mapping


def _build_output_list(replay_script: str, available: set[str]) -> list[tuple[str, str]]:
    """Returns [(fx_name, h5_key), ...] for outputs that have stored tensors."""
    fx_out = _parse_replay_out(replay_script)
    result = []
    seen = set()
    for fx_name in fx_out:
        h5_key = _fx_to_h5(fx_name, available)
        if h5_key is not None and h5_key not in seen:
            result.append((fx_name, h5_key))
            seen.add(h5_key)
    return result


def _build_expected_out(replay_script: str, available: set[str]) -> list[tuple[str, str]]:
    """Best outputs to validate: prefers final/last, falls back to all stored."""
    # Try last out first
    last = _replay_last_out(replay_script)
    last_stored = []
    for fx_name in last:
        h5_key = _fx_to_h5(fx_name, available)
        if h5_key is not None:
            last_stored.append((fx_name, h5_key))

    if last_stored:
        return last_stored

    # Fall back to all stored out
    return _build_output_list(replay_script, available)



def _tensor_metadata(h5_path: str, keys: list[str]) -> dict[str, dict]:
    """Read shape, dtype, strides, and contiguity from h5 tensor datasets."""
    _NP_TO_TORCH = {
        "float16": "float16", "float32": "float32", "float64": "float64",
        "int8": "int8", "int16": "int16", "int32": "int32", "int64": "int64",
        "uint8": "uint8", "bool": "bool",
    }
    result = {}
    with h5py.File(h5_path, "r") as f:
        grp = f.get("tensors", f)  # try /tensors/ first, then root
        for key in keys:
            if key not in grp:
                continue
            ds = grp[key]
            shape = list(ds.shape)
            torch_dtype = ds.attrs.get("torch_dtype", "")
            if torch_dtype:
                dtype_str = torch_dtype.replace("torch.", "")
            else:
                dtype_str = _NP_TO_TORCH.get(str(ds.dtype), str(ds.dtype))
            numel = 1
            for s in shape:
                numel *= s
            bytes_per = {"float32": 4, "float64": 8, "float16": 2, "bfloat16": 2,
                         "int64": 8, "int32": 4, "int16": 2, "int8": 1,
                         "uint8": 1, "bool": 1}.get(dtype_str, 4)
            entry: dict = {
                "shape": shape,
                "dtype": dtype_str,
                "numel": numel,
                "bytes": numel * bytes_per,
            }
            # Strides and contiguity (stored by op_dump)
            if "strides" in ds.attrs:
                entry["strides"] = [int(s) for s in ds.attrs["strides"]]
            if "is_contiguous" in ds.attrs:
                entry["is_contiguous"] = bool(ds.attrs["is_contiguous"])
            result[key] = entry
    return result


def _format_stride(meta: dict) -> str:
    """Format stride info as a compact string, e.g. 'strides=(512,32,1) C'."""
    strides = meta.get("strides")
    if not strides:
        return ""
    contig = meta.get("is_contiguous", True)
    flag = "C" if contig else "NC"
    s = ",".join(str(x) for x in strides)
    return f"strides=({s}) {flag}"


def _format_tensor_line(name: str, meta: dict, max_name: int = 20) -> str:
    """Format one tensor metadata line: ``name: dtype[shape]  strides  (size)``."""
    shape_str = "x".join(str(s) for s in meta["shape"]) if meta["shape"] else "scalar"
    size = meta["bytes"]
    if size >= 1024 * 1024:
        size_str = f"{size / 1024 / 1024:.1f}MB"
    elif size >= 1024:
        size_str = f"{size / 1024:.1f}KB"
    else:
        size_str = f"{size}B"
    stride_str = _format_stride(meta)
    if stride_str:
        return f"  {name:<{max_name}}  {meta['dtype']}[{shape_str}]  {stride_str}  {size_str}"
    return f"  {name:<{max_name}}  {meta['dtype']}[{shape_str}]  {size_str}"


def _op_summary(replay_script: str) -> str:
    """Summarize aten ops in a replay script."""
    from collections import Counter
    ops = re.findall(r'torch\.ops\.aten\.(\w+)', replay_script)
    getitems = replay_script.count('operator.getitem')
    counts = Counter(ops)
    parts = []
    for op, n in counts.most_common():
        parts.append(f"{op} x{n}" if n > 1 else op)
    if getitems:
        parts.append(f"getitem x{getitems}" if getitems > 1 else "getitem")
    total = len(ops) + getitems
    return f"{', '.join(parts)}  ({total} ops)"


def _build_metadata_block(
    h5_path: str,
    input_map: dict[str, str],
    output_list: list[tuple[str, str]],
    replay_script: str,
    fx_inputs: list[str],
) -> str:
    """Build a metadata comment block with tensor info and op summary."""
    all_h5_keys = list(set(
        list(input_map.values()) + [h5 for _, h5 in output_list]
    ))
    meta = _tensor_metadata(h5_path, all_h5_keys)

    lines = []
    max_name = max((len(n) for n in fx_inputs if n in input_map), default=10)
    max_name = max(max_name, max((len(fx) for fx, _ in output_list), default=10))

    # Inputs
    total_in = 0
    inp_lines = []
    for fx_name in fx_inputs:
        if fx_name not in input_map:
            continue
        h5_key = input_map[fx_name]
        if h5_key in meta:
            inp_lines.append(_format_tensor_line(fx_name, meta[h5_key], max_name))
            total_in += meta[h5_key]["bytes"]
    if inp_lines:
        in_size = f"{total_in / 1024:.1f}KB" if total_in >= 1024 else f"{total_in}B"
        lines.append(f"Inputs ({in_size} total):")
        lines.extend(inp_lines)

    # Outputs
    total_out = 0
    out_lines = []
    for fx_name, h5_key in output_list:
        if h5_key in meta:
            out_lines.append(_format_tensor_line(fx_name, meta[h5_key], max_name))
            total_out += meta[h5_key]["bytes"]
    if out_lines:
        out_size = f"{total_out / 1024:.1f}KB" if total_out >= 1024 else f"{total_out}B"
        lines.append(f"Outputs ({out_size} total):")
        lines.extend(out_lines)

    # Ops
    lines.append(f"Ops: {_op_summary(replay_script)}")

    return "\n".join(lines)


def _extract_primary_op(replay_script: str) -> str:
    """Extract the primary aten op name from a replay script for filename use."""
    # Find all aten ops, take the last non-trivial one
    ops = re.findall(r'torch\.ops\.aten\.(\w+)', replay_script)
    if ops:
        # Prefer last op that isn't a trivial getitem-producing op
        return ops[-1]
    if "operator.getitem" in replay_script:
        return "getitem"
    return "op"


_NUMERIC_RE = re.compile(r'(?<=[._])\d+(?=[._]|$)')


def _normalize_replay(replay_script: str) -> tuple[str, list[str], dict[str, str], list[str], dict[str, str]]:
    """Normalize a replay script for structural comparison.

    Replaces input/output variable names with positional markers while
    preserving aten ops, literal args, and reference structure.

    Returns:
        (normalized, generic_inputs, input_map, generic_outputs, output_map)
        - normalized: script with positional names
        - generic_inputs: ordered list of generic input names (I0, I1, ...)
        - input_map: {generic_name: original_name}
        - generic_outputs: ordered list of generic output names (O0, O1, ...)
        - output_map: {generic_name: original_name}
    """
    input_seen: dict[str, str] = {}  # original -> generic
    output_seen: dict[str, str] = {}
    input_list: list[str] = []
    output_list: list[str] = []

    def _inp_repl(m: re.Match) -> str:
        name = m.group(1)
        if name not in input_seen:
            gen = f"I{len(input_seen)}"
            input_seen[name] = gen
            input_list.append(gen)
        return f'inputs["{input_seen[name]}"]'

    def _out_assign_repl(m: re.Match) -> str:
        name = m.group(1)
        if name not in output_seen:
            gen = f"O{len(output_seen)}"
            output_seen[name] = gen
            output_list.append(gen)
        return f'outputs["{output_seen[name]}"] ='

    def _out_ref_repl(m: re.Match) -> str:
        name = m.group(1)
        if name in output_seen:
            return f'outputs["{output_seen[name]}"]'
        return m.group(0)

    lines = replay_script.strip().splitlines()
    result = []
    for line in lines:
        # Order matters: assignments first, then input refs, then output refs
        line = re.sub(r'outputs\["(\w+)"\]\s*=', _out_assign_repl, line)
        line = re.sub(r'inputs\["(\w+)"\]', _inp_repl, line)
        line = re.sub(r'outputs\["(\w+)"\]', _out_ref_repl, line)
        result.append(line)

    normalized = "\n".join(result)
    # Reverse maps: generic -> original
    inp_map = {gen: orig for orig, gen in input_seen.items()}
    out_map = {gen: orig for orig, gen in output_seen.items()}
    return normalized, input_list, inp_map, output_list, out_map


def detect_unique_groups(groups: list[GroupInfo]) -> tuple[list[UniqueGroupInfo], set[int]]:
    """Detect structurally identical groups from H5 group metadata.

    Two groups are "the same" if their replay scripts produce identical
    normalized forms (same aten ops, same literal args, same reference
    pattern — only variable names differ).

    Returns:
        (unique_groups, matched_indices) where matched_indices contains
        the group indices that belong to a unique group.
    """
    # Normalize all replay scripts
    norm_data: list[tuple[str, list[str], dict[str, str], list[str], dict[str, str]]] = []
    for g in groups:
        norm_data.append(_normalize_replay(g.replay_script))

    # Group by normalized script
    from collections import defaultdict
    buckets: dict[str, list[int]] = defaultdict(list)
    for i, (normed, *_) in enumerate(norm_data):
        buckets[normed].append(i)

    unique_groups: list[UniqueGroupInfo] = []
    matched_indices: set[int] = set()

    for normed, indices in buckets.items():
        if len(indices) < 2:
            continue

        instance_groups = [groups[i] for i in indices]

        # Derive function name from module_type or primary op
        mt = instance_groups[0].module_type
        if mt:
            # CamelCase -> snake_case
            fn = re.sub(r'(?<!^)(?=[A-Z])', '_', mt).lower()
        else:
            fn = _extract_primary_op(instance_groups[0].replay_script)

        # Build per-instance input/output maps (generic -> actual)
        input_maps = []
        output_maps = []
        for i in indices:
            _, _, inp_map, _, out_map = norm_data[i]
            input_maps.append(inp_map)
            output_maps.append(out_map)

        generic_inputs = norm_data[indices[0]][1]
        generic_outputs = norm_data[indices[0]][3]

        # Source description from first instance
        g0 = instance_groups[0]
        src_desc = g0.source_code or g0.name
        if len(src_desc) > 80:
            src_desc = src_desc[:77] + "..."

        ug = UniqueGroupInfo(
            fn_name=fn,
            module_type=mt or _extract_primary_op(g0.replay_script),
            source_line=g0.source_line,
            source_desc=src_desc,
            groups=instance_groups,
            normalized_script=normed,
            input_maps=input_maps,
            output_maps=output_maps,
            generic_inputs=generic_inputs,
            generic_outputs=generic_outputs,
        )
        unique_groups.append(ug)
        matched_indices.update(indices)

    # Disambiguate fn_names that collide — append source file stem + line
    from collections import Counter
    name_counts = Counter(ug.fn_name for ug in unique_groups)
    for ug in unique_groups:
        if name_counts[ug.fn_name] > 1:
            g0 = ug.groups[0]
            stem = Path(g0.source_file).stem if g0.source_file else ""
            ug.fn_name = f"{ug.fn_name}_{stem}_L{ug.source_line}" if stem else f"{ug.fn_name}_L{ug.source_line}"

    return unique_groups, matched_indices


def _save_test_h5(
    src_h5_path: str,
    input_map: dict[str, str],
    output_list: list[tuple[str, str]],
    dest_h5_path: str,
) -> None:
    """Save a per-test .h5 file with inputs and expected outputs.

    Follows the kernelbox naming convention (flat datasets at root):
      - Input tensors use their FX names as keys.
      - Expected outputs use ``expected_<name>`` (single) or
        ``expected_<i>_<name>`` (multiple).
      - ``torch_dtype`` attribute is set for bf16/fp16 (stored as fp32).
    """
    import numpy as np

    all_h5_keys = list(set(list(input_map.values()) + [h5 for _, h5 in output_list]))
    tensors = load_h5_tensors(src_h5_path, keys=all_h5_keys, device="cpu")

    # Build name -> tensor mapping
    data: dict[str, torch.Tensor] = {}
    for fx_name, h5_key in input_map.items():
        if h5_key in tensors:
            data[fx_name] = tensors[h5_key]
    for i, (fx_name, h5_key) in enumerate(output_list):
        if h5_key in tensors:
            if len(output_list) == 1:
                data[f"expected_{fx_name}"] = tensors[h5_key]
            else:
                data[f"expected_{i}_{fx_name}"] = tensors[h5_key]

    # dtypes that need special storage (no direct numpy equivalent)
    _NEEDS_CAST = {torch.bfloat16, torch.float16}

    Path(dest_h5_path).parent.mkdir(parents=True, exist_ok=True)
    with h5py.File(dest_h5_path, "w") as f:
        for name, t in data.items():
            if t.dtype in _NEEDS_CAST:
                # Store as float32, tag with original dtype for restoration
                arr = t.float().numpy()
                ds = f.create_dataset(name, data=arr)
                ds.attrs["torch_dtype"] = str(t.dtype)
            else:
                arr = t.numpy() if t.ndim > 0 else np.array(t.item())
                ds = f.create_dataset(name, data=arr)
                if t.dtype not in (torch.float32, torch.float64, torch.int64,
                                   torch.int32, torch.int16, torch.int8,
                                   torch.uint8, torch.bool):
                    ds.attrs["torch_dtype"] = str(t.dtype)


def _build_stride_map(h5_path: str, available: set[str]) -> dict[str, str]:
    """Build FX-name → stride comment string for all tensors in the H5 file.

    Returns a dict like ``{"add_1": "strides=(512,32,1) C", ...}``.
    """
    all_keys = list(available)
    meta = _tensor_metadata(h5_path, all_keys)
    result: dict[str, str] = {}
    # Map short h5 keys back to both short and long FX names
    for h5_key, m in meta.items():
        s = _format_stride(m)
        if s:
            result[h5_key] = s
            # Also map the long FX name (e.g. p6 -> primals_6)
            long = _long_name(h5_key)
            if long != h5_key:
                result[long] = s
    return result


def _transform_replay(
    replay_script: str,
    stride_map: dict[str, str] | None = None,
) -> str:
    """Transform replay script to use ``inputs.name`` and local variables.

    Converts:
      - ``inputs["name"]`` → ``inputs.name``
      - ``outputs["name"] = expr`` → ``name = expr``
      - ``outputs["name"]`` (RHS references) → ``name``

    When *stride_map* is provided, appends stride comments on each output line.
    """
    lines = replay_script.strip().splitlines()
    result = []
    for line in lines:
        # Extract output name before transformation (for stride lookup)
        out_match = re.match(r'outputs\["(\w+)"\]\s*=', line)
        out_name = out_match.group(1) if out_match else None

        # inputs["name"] -> inputs.name
        line = re.sub(r'inputs\["(\w+)"\]', r'inputs.\1', line)
        line = re.sub(r"inputs\['(\w+)'\]", r'inputs.\1', line)
        # outputs["name"] = ... -> name = ... (assignment)
        line = re.sub(r'outputs\["(\w+)"\]\s*=', r'\1 =', line)
        line = re.sub(r"outputs\['(\w+)'\]\s*=", r'\1 =', line)
        # outputs["name"] references on RHS -> name
        line = re.sub(r'outputs\["(\w+)"\]', r'\1', line)
        line = re.sub(r"outputs\['(\w+)'\]", r'\1', line)

        # Append stride comment for output
        if stride_map and out_name:
            h5_key = _short_name(out_name)
            stride_str = stride_map.get(h5_key) or stride_map.get(out_name)
            if stride_str:
                line = f"{line}  # {stride_str}"

        result.append(line)
    return "\n".join(result)


def _save_unique_instance_h5(
    src_h5_path: str,
    input_map: dict[str, str],  # generic_name -> actual FX name (this instance)
    output_map: dict[str, str],  # generic_name -> actual FX name (this instance)
    canonical_inputs: dict[str, str],  # generic_name -> canonical key name (first instance's names)
    canonical_outputs: dict[str, str],  # generic_name -> canonical key name
    expected_generics: set[str],
    available: set[str],
    dest_h5_path: str,
) -> None:
    """Save a .h5 data file for one instance of a unique group.

    Keys use the first instance's FX names (canonical) so ``run(inputs)``
    works identically for all instances.
    """
    import numpy as np

    # Collect h5 keys needed
    all_h5_keys: list[str] = []
    for gen_name, fx_name in input_map.items():
        h5_key = _fx_to_h5(fx_name, available)
        if h5_key:
            all_h5_keys.append(h5_key)
    for gen_name, fx_name in output_map.items():
        if gen_name in expected_generics:
            h5_key = _fx_to_h5(fx_name, available)
            if h5_key:
                all_h5_keys.append(h5_key)

    tensors = load_h5_tensors(src_h5_path, keys=all_h5_keys, device="cpu")

    _NEEDS_CAST = {torch.bfloat16, torch.float16}
    data: dict[str, torch.Tensor] = {}

    # Inputs: store under canonical name (first instance's FX name)
    for gen_name, fx_name in input_map.items():
        h5_key = _fx_to_h5(fx_name, available)
        canon = canonical_inputs.get(gen_name, gen_name)
        if h5_key and h5_key in tensors:
            data[canon] = tensors[h5_key]

    # Expected outputs: store under expected_<canonical_name>
    exp_list = [(gen, fx_name) for gen, fx_name in output_map.items()
                if gen in expected_generics]
    for i, (gen_name, fx_name) in enumerate(exp_list):
        h5_key = _fx_to_h5(fx_name, available)
        canon = canonical_outputs.get(gen_name, gen_name)
        if h5_key and h5_key in tensors:
            if len(exp_list) == 1:
                data[f"expected_{canon}"] = tensors[h5_key]
            else:
                data[f"expected_{i}_{canon}"] = tensors[h5_key]

    Path(dest_h5_path).parent.mkdir(parents=True, exist_ok=True)
    with h5py.File(dest_h5_path, "w") as f:
        for name, t in data.items():
            if t.dtype in _NEEDS_CAST:
                arr = t.float().numpy()
                ds = f.create_dataset(name, data=arr)
                ds.attrs["torch_dtype"] = str(t.dtype)
            else:
                arr = t.numpy() if t.ndim > 0 else np.array(t.item())
                ds = f.create_dataset(name, data=arr)
                if t.dtype not in (torch.float32, torch.float64, torch.int64,
                                   torch.int32, torch.int16, torch.int8,
                                   torch.uint8, torch.bool):
                    ds.attrs["torch_dtype"] = str(t.dtype)


def _instance_label(group: GroupInfo) -> str:
    """Short label for a unique group instance, e.g. 'blocks_0' from 'self.blocks.0.ln_1'."""
    mp = group.module_path or ""
    # Extract the varying part — typically the numeric index in the path
    parts = mp.replace("self.", "").split(".")
    # Find parts with numbers and take the prefix up to and including the number
    for i, p in enumerate(parts):
        if p.isdigit():
            return "_".join(parts[:i+1])
    # Fallback: use group index
    return f"instance_{group.index:03d}"


def generate_unique_group_script(
    h5_path: str,
    ug: UniqueGroupInfo,
    out_dir: str,
    available: set[str] | None = None,
) -> str:
    """Generate a kbox file + h5_suite directory for a uniquified group.

    Produces:
      - ``grp_<fn_name>.py`` — one ``run()`` function for all instances
      - ``data/grp_<fn_name>/`` — directory with one .h5 per instance

    Uses kernelbox's ``h5_suite`` contract: ``init_once()`` returns
    ``{"h5_suite": "data/grp_<fn_name>/"}`` and kernelbox tests each
    .h5 file against the same ``run()``.
    """
    if available is None:
        available = _available_tensors(h5_path)

    # Determine which generic outputs to validate (last meaningful outputs)
    expected_generics = set()
    # Use the first instance's replay to determine expected outputs
    g0 = ug.groups[0]
    exp_out = _build_expected_out(g0.replay_script, available)
    for fx_name, _ in exp_out:
        # Find which generic name maps to this fx_name
        for gen, actual in ug.output_maps[0].items():
            if actual == fx_name:
                expected_generics.add(gen)

    # Canonical names = first instance's actual FX names
    canonical_inputs = ug.input_maps[0]   # {generic -> first instance's FX name}
    canonical_outputs = ug.output_maps[0]

    # Save per-instance h5 data files
    suite_rel = f"data/grp_{ug.fn_name}"
    suite_abs = os.path.join(out_dir, suite_rel)
    for i, g in enumerate(ug.groups):
        label = _instance_label(g)
        inst_path = os.path.join(suite_abs, f"{label}.h5")
        _save_unique_instance_h5(
            h5_path, ug.input_maps[i], ug.output_maps[i],
            canonical_inputs, canonical_outputs,
            expected_generics, available, inst_path,
        )

    # Build stride map from first instance's tensors
    stride_map = _build_stride_map(h5_path, available)

    # Build the script — use first instance's names for readability
    replay = ug.normalized_script
    # Replace generic I0/O0 markers with first instance's actual names
    first_inp = ug.input_maps[0]  # {generic -> actual}
    first_out = ug.output_maps[0]
    for gen, actual in first_inp.items():
        replay = replay.replace(f'inputs["{gen}"]', f'inputs["{actual}"]')
    for gen, actual in first_out.items():
        replay = replay.replace(f'outputs["{gen}"]', f'outputs["{actual}"]')
        replay = re.sub(rf'\b{re.escape(gen)}\b(?!\w)', actual, replay)
    replay_body = _transform_replay(replay, stride_map=stride_map)
    replay_indented = textwrap.indent(replay_body, "    ")

    # Imports
    imports = ["import torch"]
    if "operator.getitem" in replay:
        imports.append("import operator")
    if _needs_math(replay):
        imports.append("import math")
    imports_block = "\n".join(imports)

    # Return the expected outputs (using first instance's actual names)
    first_out = ug.output_maps[0]
    exp_actual_ordered = [first_out[g] for g in ug.generic_outputs if g in expected_generics]
    if exp_actual_ordered:
        ret_items = ", ".join(exp_actual_ordered)
        ret_stmt = f"    return [{ret_items}]"
    else:
        ret_stmt = "    return []"

    # Instance labels for docstring
    labels = [_instance_label(g) for g in ug.groups]
    instances_str = ", ".join(labels)

    # Tensor metadata from first instance
    g0 = ug.groups[0]
    first_inp = ug.input_maps[0]
    first_out = ug.output_maps[0]
    # Build input_map and output_list in the format _build_metadata_block expects
    g0_input_map = _build_input_mapping(g0.replay_script, available)
    g0_output_list = _build_expected_out(g0.replay_script, available)
    g0_fx_inputs = _parse_replay_inputs(g0.replay_script)
    meta_block = _build_metadata_block(h5_path, g0_input_map, g0_output_list,
                                        g0.replay_script, g0_fx_inputs)

    py_name = f"grp_{ug.fn_name}.py"
    doc = f'"""{ug.module_type} ({len(ug.groups)} instances: {instances_str})\n{ug.source_desc}\n\n{meta_block}\n\n    kbox iterate {py_name}\n"""'

    init_block = f'def init_once():\n    return {{"h5_suite": "{suite_rel}/"}}'

    # Input stride comments for the first instance
    input_stride_lines = []
    g0_fx_inputs_for_strides = _parse_replay_inputs(g0.replay_script)
    for fx_name in g0_fx_inputs_for_strides:
        h5_key = _fx_to_h5(fx_name, available)
        s = stride_map.get(h5_key) if h5_key else stride_map.get(fx_name)
        if s:
            input_stride_lines.append(f"    # {fx_name}: {s}")
    input_strides_block = "\n".join(input_stride_lines)

    run_parts = [f"def run(inputs):"]
    if input_stride_lines:
        run_parts.append(input_strides_block)
    run_parts.append(replay_indented)
    run_parts.append(ret_stmt)
    run_block = "\n".join(run_parts)

    script = f"""\
{doc}
{imports_block}


{init_block}


{run_block}
"""
    script = re.sub(r'\n{3,}', '\n\n\n', script)

    out_path = os.path.join(out_dir, py_name)
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    Path(out_path).write_text(script)

    return script


def _data_relpath(out_path: str, group: GroupInfo) -> str:
    """Compute the relative path to the .h5 data file from the test script."""
    h5_name = _group_filename(group).replace(".py", ".h5")
    return f"data/{h5_name}"


def generate_group_script(
    h5_path: str,
    group: GroupInfo,
    out_path: str | None = None,
    available: set[str] | None = None,
    validate: bool = False,
) -> str:
    """Generate a kbox-watch-compatible test file for one group.

    Produces a clean kernelbox-style script:
      - ``init_once()`` returns ``{"h5": "data/<name>.h5"}``
      - ``run(inputs)`` uses ``inputs.<name>`` attribute access
      - A per-test ``.h5`` data file is saved alongside the script

    Args:
        validate: If True, append a standalone ``__main__`` validation block.
    """
    if available is None:
        available = _available_tensors(h5_path)

    input_map = _build_input_mapping(group.replay_script, available)
    output_list = _build_expected_out(group.replay_script, available)
    output_fx_names = [fx for fx, _ in output_list]

    # Detect missing inputs
    fx_inputs = _parse_replay_inputs(group.replay_script)
    missing = [n for n in fx_inputs if n not in input_map]

    # Save .h5 data file when we have an output path
    data_rel = _data_relpath(out_path or "", group)
    if out_path:
        data_abs = os.path.join(os.path.dirname(os.path.abspath(out_path)), data_rel)
        _save_test_h5(h5_path, input_map, output_list, data_abs)

    # Imports — only what's needed
    imports = ["import torch"]
    if "operator.getitem" in group.replay_script:
        imports.append("import operator")
    if _needs_math(group.replay_script):
        imports.append("import math")

    # Docstring with tensor metadata
    basename = os.path.basename(out_path) if out_path else "test.py"
    meta_block = _build_metadata_block(h5_path, input_map, output_list,
                                        group.replay_script, fx_inputs)
    doc = f'"""{group.name}\n\n{meta_block}\n\n    kbox iterate {basename}\n"""'

    # init_once — just point at the .h5 data file
    init_block = f'def init_once():\n    return {{"h5": "{data_rel}"}}'

    # Build stride map for inline comments
    stride_map = _build_stride_map(h5_path, available)

    # Input stride comments block
    input_stride_lines = []
    for fx_name in fx_inputs:
        if fx_name not in input_map:
            continue
        h5_key = input_map[fx_name]
        s = stride_map.get(h5_key) or stride_map.get(fx_name)
        if s:
            input_stride_lines.append(f"    # {fx_name}: {s}")
    input_strides_block = "\n".join(input_stride_lines)

    # Transform replay script to use inputs.name and local variables
    replay_body = _transform_replay(group.replay_script, stride_map=stride_map)
    replay_indented = textwrap.indent(replay_body, "    ")

    # Return statement
    if output_fx_names:
        ret_items = ", ".join(output_fx_names)
        ret_stmt = f"    return [{ret_items}]"
    else:
        ret_stmt = "    return []"

    run_parts = [f"def run(inputs):"]
    if input_stride_lines:
        run_parts.append(input_strides_block)
    run_parts.append(replay_indented)
    run_parts.append(ret_stmt)
    run_block = "\n".join(run_parts)

    # Missing inputs warning
    missing_comment = ""
    if missing:
        missing_str = ", ".join(missing)
        missing_comment = f"\n# WARNING: Missing tensors: {missing_str}\n"

    imports_block = "\n".join(imports)

    # Validation block
    check_block = ""
    if validate and output_list:
        check_block = textwrap.dedent("""\

            if __name__ == "__main__":
                import kernelbox as kbox
                kbox.iterate(__file__)
            """)

    script = f"""\
{doc}
{imports_block}
{missing_comment}

{init_block}


{run_block}
{check_block}"""

    # Clean up extra blank lines
    script = re.sub(r'\n{3,}', '\n\n\n', script)

    if out_path:
        Path(out_path).parent.mkdir(parents=True, exist_ok=True)
        Path(out_path).write_text(script)

    return script


def _collect_ops_toposorted(h5_path: str, section: str, strategy: str) -> list[tuple[str, str]]:
    """Collect all per-op replay scripts, topologically sorted by data deps.

    When multiple ops are ready, prefers ops from the same group (source line)
    as the last emitted op, then falls back to lowest group index.  This keeps
    ops from the same line of code together for readability.

    Returns [(group_name, replay_line), ...] in correct execution order.
    """
    ops_raw: list[tuple[str, str, str, list[str], int]] = []
    group_names: list[str] = []

    # Build the section path — try "section/strategy" first, fall back to bare strategy
    section_path = f"{section}/{strategy}"

    with h5py.File(h5_path, "r") as f:
        if section_path not in f:
            # Try bare strategy or "groups" for single-graph captures
            if strategy in f:
                section_path = strategy
            elif "groups" in f:
                section_path = "groups"
            else:
                return []
        parent = f[section_path]
        for gi, gk in enumerate(sorted(parent.keys())):
            group_names.append(gk)
            grp = parent[gk]
            for sk in sorted(grp.keys()):
                item = grp[sk]
                if not isinstance(item, h5py.Group):
                    continue
                rs = item.attrs.get("replay_script", "")
                if not rs:
                    continue
                out_m = re.match(r'outputs\["(\w+)"\]', rs)
                out_name = out_m.group(1) if out_m else ""
                in_names = re.findall(r'(?:inputs|outputs)\["(\w+)"\]', rs)
                in_names = [n for n in in_names if n != out_name]
                ops_raw.append((gk, rs, out_name, in_names, gi))

    name_to_producer: dict[str, int] = {}
    for i, (_, _, out_name, _, _) in enumerate(ops_raw):
        if out_name:
            name_to_producer[out_name] = i

    in_degree = [0] * len(ops_raw)
    dependents: list[list[int]] = [[] for _ in range(len(ops_raw))]
    for i, (_, _, _, in_names, _) in enumerate(ops_raw):
        for inp in in_names:
            producer = name_to_producer.get(inp)
            if producer is not None and producer != i:
                in_degree[i] += 1
                dependents[producer].append(i)

    import heapq
    ready: list[tuple[int, int, int]] = []  # (group_idx, original_pos, op_idx)
    for i, (_, _, _, _, gi) in enumerate(ops_raw):
        if in_degree[i] == 0:
            heapq.heappush(ready, (gi, i, i))

    result: list[tuple[str, str]] = []
    while ready:
        _, _, idx = heapq.heappop(ready)
        gname, rs, _, _, _ = ops_raw[idx]
        result.append((gname, rs))
        for dep in dependents[idx]:
            in_degree[dep] -= 1
            if in_degree[dep] == 0:
                _, _, _, _, dep_gi = ops_raw[dep]
                heapq.heappush(ready, (dep_gi, dep, dep))

    if len(result) < len(ops_raw):
        for i in range(len(ops_raw)):
            if in_degree[i] > 0:
                gname, rs, _, _, _ = ops_raw[i]
                result.append((gname, rs))

    return result


def generate_section_script(
    h5_path: str,
    section: str,
    strategy: str = "line",
    out_path: str | None = None,
    validate: bool = False,
) -> str:
    """Generate a test that chains all ops in a section, topologically sorted by deps.

    Args:
        validate: If True, append a ``check()`` block that compares ``run()``
            output against ``expected`` using ``torch.allclose``.
    """
    groups = list_groups(h5_path, section=section, strategy=strategy)
    if not groups:
        raise ValueError(f"No groups found for {section}/{strategy}")

    ops = _collect_ops_toposorted(h5_path, section, strategy)
    available = _available_tensors(h5_path)
    h5_basename = os.path.basename(h5_path)

    # Collect all external inputs and expected outputs
    all_input_keys: dict[str, str] = {}
    needs_math_mod = False

    for _, rs in ops:
        if _needs_math(rs):
            needs_math_mod = True

    for g in groups:
        inp_map = _build_input_mapping(g.replay_script, available)
        for fx, h5 in inp_map.items():
            all_input_keys[fx] = h5

    # Expected: last output of each group for section-level validation
    expected_pairs: list[tuple[str, str]] = []
    for g in groups:
        for fx, h5 in _build_expected_out(g.replay_script, available):
            expected_pairs.append((fx, h5))
    # Deduplicate (keep last occurrence per fx_name)
    seen_expected: dict[str, str] = {}
    for fx, h5 in expected_pairs:
        seen_expected[fx] = h5
    expected_pairs = list(seen_expected.items())
    expected_fx_names = [fx for fx, _ in expected_pairs]

    # Save .h5 data file
    data_rel = f"data/{section}_{strategy}_chain.h5"
    if out_path:
        data_abs = os.path.join(os.path.dirname(os.path.abspath(out_path)), data_rel)
        _save_test_h5(h5_path, all_input_keys, expected_pairs, data_abs)

    # Build script
    basename = os.path.basename(out_path) if out_path else "chain.py"
    doc = f'"""{section}/{strategy} — {len(ops)} ops from {len(groups)} groups\n\n    kbox iterate {basename}\n"""'

    imports = ["import torch"]
    if any("operator.getitem" in rs for _, rs in ops):
        imports.append("import operator")
    if needs_math_mod:
        imports.append("import math")
    imports_block = "\n".join(imports)

    init_block = f'def init_once():\n    return {{"h5": "{data_rel}"}}'

    # Build stride map for inline comments
    stride_map = _build_stride_map(h5_path, available)

    # Run function — flat ops in topological order using local variables
    produced: set[str] = set()
    for _, rs in ops:
        m = re.match(r'outputs\["(\w+)"\]\s*=', rs.strip())
        if m:
            produced.add(m.group(1))

    def _ref(name: str) -> str:
        return name if name in produced else f'inputs.{name}'

    run_lines = ["def run(inputs):"]

    # Input stride comments
    for fx_name in sorted(all_input_keys.keys()):
        h5_key = all_input_keys[fx_name]
        s = stride_map.get(h5_key) or stride_map.get(fx_name)
        if s:
            run_lines.append(f"    # {fx_name}: {s}")

    prev_group = None
    for gname, rs in ops:
        if gname != prev_group:
            short = gname if len(gname) <= 80 else gname[:77] + "..."
            run_lines.append(f"    # ── {short} ──")
            prev_group = gname
        line = rs.strip()
        m = re.match(r'outputs\["(\w+)"\]\s*=\s*(.*)', line)
        if m:
            oname, expr = m.group(1), m.group(2)
            expr = re.sub(r'(?:outputs|inputs)\["(\w+)"\]', lambda m: _ref(m.group(1)), expr)
            stride_comment = ""
            h5_key = _short_name(oname)
            s = stride_map.get(h5_key) or stride_map.get(oname)
            if s:
                stride_comment = f"  # {s}"
            run_lines.append(f'    {oname} = {expr}{stride_comment}')
        else:
            run_lines.append(f"    {line}")

    run_lines.append("")
    ret_items = ", ".join(expected_fx_names)
    run_lines.append(f"    return [{ret_items}]")

    run_block = "\n".join(run_lines)

    # Validation block
    check_block = ""
    if validate and expected_pairs:
        check_block = textwrap.dedent("""\

            if __name__ == "__main__":
                import kernelbox as kbox
                kbox.iterate(__file__)
            """)

    script = f"""\
{doc}
{imports_block}


{init_block}


{run_block}
{check_block}"""

    # Clean up extra blank lines
    script = re.sub(r'\n{3,}', '\n\n\n', script)

    if out_path:
        Path(out_path).parent.mkdir(parents=True, exist_ok=True)
        Path(out_path).write_text(script)

    return script


def _group_filename(group: GroupInfo) -> str:
    """Generate a clean, short filename for a group.

    Format: ``fw_NNN_<op>.py`` or ``bw_NNN_<op>.py`` where NNN is the
    zero-padded group index and <op> is the primary aten operation.
    """
    prefix = "bw" if group.section == "backward" else "fw"
    op = _extract_primary_op(group.replay_script)
    return f"{prefix}_{group.index:03d}_{op}.py"


def generate_all(
    h5_path: str,
    out_dir: str,
    section: str | None = None,
    strategy: str = "line",
    validate: bool = False,
    uniquify: bool = True,
) -> list[str]:
    """Generate test files for all groups. Returns list of generated file paths.

    When ``uniquify=True``, structurally identical groups are collapsed into
    a single ``grp_<name>.py`` with an ``h5_suite`` of per-instance data files.
    Remaining (non-duplicated) groups get individual ``fw_NNN_<op>.py`` files.
    """
    groups = list_groups(h5_path, section=section, strategy=strategy)
    available = _available_tensors(h5_path)
    out_dir_path = Path(out_dir)
    out_dir_path.mkdir(parents=True, exist_ok=True)

    matched_indices: set[int] = set()
    paths: list[str] = []

    if uniquify:
        unique_groups, matched_indices = detect_unique_groups(groups)
        for ug in unique_groups:
            generate_unique_group_script(h5_path, ug, str(out_dir_path),
                                         available=available)
            paths.append(str(out_dir_path / f"grp_{ug.fn_name}.py"))

    for g in groups:
        if g.index in matched_indices:
            continue
        filename = _group_filename(g)
        out_path = str(out_dir_path / filename)
        generate_group_script(h5_path, g, out_path=out_path, available=available,
                              validate=validate)
        paths.append(out_path)

    return paths


def kbox_cli() -> None:
    """CLI entry point for ``python -m torch_graph kbox``."""
    import argparse

    parser = argparse.ArgumentParser(
        prog="torch_graph kbox",
        description="Generate kbox test scripts from an H5 tensor dump.",
    )
    parser.add_argument("h5_file", help="Path to H5 file produced by torch-graph dump")
    parser.add_argument(
        "--section",
        choices=["forward", "backward", "both"],
        default="forward",
        help="Which section(s) to generate scripts for (default: forward)",
    )
    parser.add_argument(
        "--strategy",
        choices=["line", "module"],
        default="line",
        help="Grouping strategy (default: line)",
    )
    parser.add_argument(
        "--out-dir",
        default=None,
        help="Output directory (default: derived from H5 filename)",
    )
    parser.add_argument(
        "--chain",
        action="store_true",
        help="Generate a single chained section script instead of per-group scripts",
    )
    parser.add_argument(
        "--validate",
        action="store_true",
        help="Add validation/check code to generated scripts",
    )

    args = parser.parse_args()

    h5_path = os.path.abspath(args.h5_file)
    if not os.path.isfile(h5_path):
        print(f"Error: H5 file not found: {h5_path}")
        raise SystemExit(1)

    out_dir = args.out_dir
    if out_dir is None:
        stem = Path(h5_path).stem
        out_dir = f"{stem}_kbox"

    sections = ["forward", "backward"] if args.section == "both" else [args.section]

    total_files = []
    for sec in sections:
        if args.chain:
            out_path = os.path.join(out_dir, f"{sec}_{args.strategy}_chain.py")
            try:
                generate_section_script(
                    h5_path, section=sec, strategy=args.strategy,
                    out_path=out_path, validate=args.validate,
                )
                total_files.append(out_path)
            except ValueError as e:
                print(f"  Skipping {sec}/{args.strategy}: {e}")
        else:
            paths = generate_all(
                h5_path, out_dir=out_dir, section=sec,
                strategy=args.strategy, validate=args.validate,
            )
            total_files.extend(paths)

    print(f"Generated {len(total_files)} file(s) in {out_dir}/")
    for p in total_files:
        print(f"  {p}")
